version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devconnect_api
    ports:
      - "8082:8082"
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=Kadeira4.0
      - KAFKA_SERVER=kafka:9092
      - AUTH_URL=app:8080
    depends_on:
      - neo4j
    networks:
      - dev-connect

  neo4j:
    image: neo4j:latest
    container_name: devconnect_neo4j
    ports:
      - "7474:7474"
      - "7687:7687" 
    environment:
      - NEO4J_AUTH=neo4j/Kadeira4.0
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - dev-connect
volumes:
  neo4j_data:
  neo4j_logs:

networks:
  dev-connect:
    external: true